//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public string id_booking { get; set; }
        public string id_ticket { get; set; }
        public string id_passenger { get; set; }
        public string id_employee { get; set; }
        public Nullable<System.DateTime> booking_time { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PASSENGER PASSENGER { get; set; }
        public virtual TICKET TICKET { get; set; }
    }
}
