//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSROUTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUSROUTE()
        {
            this.TRIPs = new HashSet<TRIP>();
            this.BUSSTATIONs = new HashSet<BUSSTATION>();
        }
    
        public string id_route { get; set; }
        public string id_start_station { get; set; }
        public string id_end_station { get; set; }
        public double distance { get; set; }
    
        public virtual BUSSTATION BUSSTATION { get; set; }
        public virtual BUSSTATION BUSSTATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIP> TRIPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUSSTATION> BUSSTATIONs { get; set; }
    }
}
