//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BOOKINGINFOR
    {
        public string Booking_ID { get; set; }
        public string Passenger_ID { get; set; }
        public string Ticket_ID { get; set; }
        public string Passenger_name { get; set; }
        public Nullable<bool> Passenger_gender { get; set; }
        public string Passenger_phone_number { get; set; }
        public string Employee_name { get; set; }
        public Nullable<bool> Employee_gender { get; set; }
        public string Employee_phone_number { get; set; }
        public Nullable<System.DateTime> Booking_time { get; set; }
    }
}
