//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DRIVERINFOR
    {
        public string Employees_ID { get; set; }
        public string Name { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Lisence_Level { get; set; }
        public string Type { get; set; }
        public string State { get; set; }
    }
}
