//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGE
    {
        public string id_package { get; set; }
        public string id_trip { get; set; }
        public Nullable<double> mass { get; set; }
        public Nullable<decimal> price { get; set; }
        public string sender_contact_phone { get; set; }
        public string receiver_contact_phone { get; set; }
    
        public virtual TRIP TRIP { get; set; }
    }
}
