//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    
    public partial class pro_DisableEmployee_Result1
    {
        public string id_employee { get; set; }
        public string id_account { get; set; }
        public string id_agent { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string identity_number { get; set; }
        public decimal salary { get; set; }
        public string email { get; set; }
        public System.DateTime birthdate { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<bool> state { get; set; }
    }
}
