//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BUSSTATIONINFOR
    {
        public string id_place { get; set; }
        public string Phone_number { get; set; }
        public string Address { get; set; }
        public string Region { get; set; }
    }
}
