//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicketManagementApplication.src.dbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EMPLOYEEINFOR
    {
        public string Employees_ID { get; set; }
        public string Name { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Identity_number { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> State { get; set; }
        public string Position { get; set; }
    }
}
